@baseUrl = http://localhost:PORT

GET {{baseUrl}}/api/health

###

GET {{baseUrl}}/api/workflow/applications

###

POST {{baseUrl}}/api/workflow/applications

###

PUT {{baseUrl}}/api/workflow/applications/1/status
